<?php
/**
 * Created by PhpStorm.
 * User: xiehuanjin
 * Date: 2019/1/12
 * Time: 19:50
 */

namespace App\Component\Log;


class KernelBusMonitor extends Elog
{

    public function process($level, $trace, $message, $context)
    {
        parent::process($level, $trace, $message, $context); // TODO: Change the autogenerated stub
    }

}